name: Go Test

on:
  pull_request:
  push:
    tags:
    - '**'
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod # Use whatever version is in the header of go.mod.

    - name: Vendor and patch SDK
      run: make deps

    - name: Test
      run: go test -timeout=5m ./...
